### ISSUE TITLE
Feature: User can view options of cryptos

### ISSUE THREAD

**Issue by NicholasProdehl** [NicholasProdehl/ajax-Project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view options of Crypto currencies to add.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can select which crypto to add and the amount to add. They can view the current prices of each currency.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-11-10 at 1 55 55 PM](https://user-images.githubusercontent.com/90858352/141184066-740bbecb-b3eb-45da-9b9b-5e663167b110.png)
![Screen Shot 2021-11-10 at 1 55 33 PM](https://user-images.githubusercontent.com/90858352/141184013-9ed65dba-1175-4962-9ac6-17c2684084b9.png)
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create div[data-view="entry-form"]
- [x] Set background to the cool Bitcoin image.
- [x] create header including 2 buttons for different data-views and logo
- [x] Create left-side bar including 10 buttons for the currencies and their respective current prices.
- [x] Create Crypto Portfolio title
- [x] Create Selector input with the 10 currencies
- [x] Create Amount text input.
- [x] Create button for "Change Holdings."

- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
