### ISSUE TITLE
Feature: User can input the amounts of said crypto they select.

### ISSUE THREAD

**Issue by NicholasProdehl** [NicholasProdehl/ajax-Project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can store values of their added crypto to their portfolio.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once selecting the crypto they're adding and how much, they will be pushed to the page appropriate to that crypto.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="186" alt="Screen Shot 2021-11-12 at 12 47 03 PM" src="https://user-images.githubusercontent.com/90858352/141519138-81bb6a79-d2ae-42ee-be6b-7a1a7f00f040.png">

<img width="186" alt="Screen Shot 2021-11-12 at 12 46 33 PM" src="https://user-images.githubusercontent.com/90858352/141519078-d2f41b21-2eac-478f-8269-bceb41c36c8b.png">
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [x] create html for the "Total Valuation" page
- [x] create html setup bitcoin valuation page.
- [x] recreate html setup for the rest of the cryptos valuation pages.
- [x] input the dollar-image.jpeg into the pages.
- [ ] Query the DOM for buttons from homepage to access crypto value pages.
- [ ] Query the DOM to store the object saved on homepage to a data object.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
